### ISSUE TITLE
Plugin fails when no expression exists after if or else if

### ISSUE THREAD

**Issue by evgygor** [RokuRoad/eslint-plugin-roku#28]
The following code examples cause to eslint crash:

```
if <condition> then
    else <condition> then
```
```
if <condition> then
    else
```
**The exceptions is:**
```
_Cannot read property 'range' of undefined
TypeError: Cannot read property 'range' of undefined
    at SourceCode.getTokensBefore (C:\Git_works\main\node_modules\eslint\lib\token-store\index.js:446:18)
    at Object.getTokensBefore (C:\Git_works\main\node_modules\eslint\lib\linter.js:739:96)
    at IfStatement (C:\Git_works\main\node_modules\eslint-plugin-roku\dist\rules\no-shorthand-if.js:25:32)
    at listeners.(anonymous function).forEach.listener (C:\Git_works\main\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Git_works\main\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Git_works\main\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Git_works\main\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Git_works\main\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\Git_works\main\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)_
```
**Current workaround is adding comment ' sign:**
```
if <condition> then
    '
    else <condition> then
```
```
if <condition> then
   '
    else
```

**Comment by evgygor** [comment]
Fix provided in [PR27](https://github.com/RokuRoad/eslint-plugin-roku/pull/27)
